=== Tebogo-Phasha/C-Expression-builder/wordProcessingML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="p" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="pPr">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="spacing" />
                    <xs:element name="numPr" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="ilvl" />
                          <xs:element name="numId" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="ind" minOccurs="0" />
                    <xs:element name="contextualSpacing" minOccurs="0" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="r" minOccurs="0">
                <xs:complexType>
                  <xs:sequence minOccurs="0">
                    <xs:element name="t" minOccurs="0" type="xs:string" />
                    <xs:element name="br" minOccurs="0" />
                    <xs:element name="rPr" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence minOccurs="0">
                          <xs:element name="b" minOccurs="0" />
                          <xs:element name="bCs" minOccurs="0" />
                          <xs:element name="u" minOccurs="0" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Tebogo-Phasha/C-Expression-builder/wordProcessingML.xml
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="wordProcessingML.xsd">
    <w:p xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
      <w:pPr>
        <w:spacing w:line="240" w:lineRule="auto" />
      </w:pPr>
      <w:r>
        <w:t>This is a test 123</w:t>
      </w:r>
    </w:p>
    <w:p xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
      <w:pPr>
        <w:spacing w:line="240" w:lineRule="auto" />
      </w:pPr>
    </w:p>
    <w:p xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
      <w:pPr>
        <w:numPr>
          <w:ilvl w:val="0" />
          <w:numId w:val="1" />
        </w:numPr>
        <w:spacing w:beforeAutospacing="1" w:afterAutospacing="1" w:line="240" w:lineRule="auto" />
        <w:ind w:left="780" w:right="180" />
        <w:contextualSpacing />
      </w:pPr>
      <w:r>
        <w:t>1 Bullet list</w:t>
      </w:r>
    </w:p>
    <w:p xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
      <w:pPr>
        <w:numPr>
          <w:ilvl w:val="1" />
          <w:numId w:val="1" />
        </w:numPr>
        <w:spacing w:beforeAutospacing="1" w:afterAutospacing="1" w:line="240" w:lineRule="auto" />
        <w:ind w:left="1380" w:right="180" />
      </w:pPr>
      <w:r>
        <w:t>2 Indented number</w:t>
      </w:r>
    </w:p>
    <w:p xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
      <w:pPr>
        <w:numPr>
          <w:ilvl w:val="0" />
          <w:numId w:val="1" />
        </w:numPr>
        <w:spacing w:beforeAutospacing="1" w:afterAutospacing="1" w:line="240" w:lineRule="auto" />
        <w:ind w:left="780" w:right="180" />
      </w:pPr>
      <w:r>
        <w:t>3</w:t>
      </w:r>
    </w:p>
    <w:p xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
      <w:pPr>
        <w:spacing w:line="240" w:lineRule="auto" />
      </w:pPr>
      <w:r>
        <w:br />
      </w:r>
    </w:p>
    <w:p xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
      <w:pPr>
        <w:numPr>
          <w:ilvl w:val="0" />
          <w:numId w:val="2" />
        </w:numPr>
        <w:spacing w:beforeAutospacing="1" w:afterAutospacing="1" w:line="240" w:lineRule="auto" />
        <w:ind w:left="780" w:right="180" />
        <w:contextualSpacing />
      </w:pPr>
      <w:r>
        <w:t>Text</w:t>
      </w:r>
    </w:p>
    <w:p xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
      <w:pPr>
        <w:numPr>
          <w:ilvl w:val="0" />
          <w:numId w:val="2" />
        </w:numPr>
        <w:spacing w:beforeAutospacing="1" w:afterAutospacing="1" w:line="240" w:lineRule="auto" />
        <w:ind w:left="780" w:right="180" />
      </w:pPr>
      <w:r>
        <w:t>Numbered List</w:t>
      </w:r>
    </w:p>
    <w:p xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
      <w:pPr>
        <w:spacing w:line="240" w:lineRule="auto" />
      </w:pPr>
    </w:p>
    <w:p xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
      <w:pPr>
        <w:spacing w:line="240" w:lineRule="auto" />
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:b />
          <w:bCs />
        </w:rPr>
        <w:t>Bold</w:t>
      </w:r>
    </w:p>
    <w:p xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
      <w:pPr>
        <w:spacing w:line="240" w:lineRule="auto" />
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:u w:val="single" />
        </w:rPr>
        <w:t>Underlined</w:t>
      </w:r>
    </w:p>
    <w:p xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
      <w:pPr>
        <w:spacing w:line="240" w:lineRule="auto" />
      </w:pPr>
    </w:p>
  </root>
